version: "3.9"

services:
  app:
    build: .
    container_name: notification_service
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      APP_PORT: ${APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      RABBITMQ_URL: ${RABBITMQ_URL}

  postgres:
    image: postgres:15
    container_name: postgres_notifications
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_notifications
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
